; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.34"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[nobcc][download][type] = ""
projects[nobcc][download][url] = ""
projects[nobcc][type] = "profile"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[civicrm][download][type] = ""
projects[civicrm][download][url] = ""
projects[civicrm][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[civicrm_contact_ref][download][type] = ""
projects[civicrm_contact_ref][download][url] = ""
projects[civicrm_contact_ref][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[civicrm_engage][download][type] = ""
projects[civicrm_engage][download][url] = ""
projects[civicrm_engage][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[civicrm_group_roles][download][type] = ""
projects[civicrm_group_roles][download][url] = ""
projects[civicrm_group_roles][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[civicrm_member_roles][download][type] = ""
projects[civicrm_member_roles][download][url] = ""
projects[civicrm_member_roles][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[civicrm_og_sync][download][type] = ""
projects[civicrm_og_sync][download][url] = ""
projects[civicrm_og_sync][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[civicrm_rules][download][type] = ""
projects[civicrm_rules][download][url] = ""
projects[civicrm_rules][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[civicrmtheme][download][type] = ""
projects[civicrmtheme][download][url] = ""
projects[civicrmtheme][type] = "module"

